#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_SVG="$ROOT_DIR/AppResources/AppIcon-Timeline.svg"
OUT_ICNS="$ROOT_DIR/AppResources/AppIcon.icns"

if [[ ! -f "$SRC_SVG" ]]; then
  echo "[icon] Missing source SVG: $SRC_SVG" >&2
  exit 1
fi

TMP_DIR="$ROOT_DIR/.build/appicon-tmp"
ICONSET_DIR="$ROOT_DIR/.build/AppIcon.iconset"

rm -rf "$TMP_DIR" "$ICONSET_DIR"
mkdir -p "$TMP_DIR" "$ICONSET_DIR"

# Render SVG to a 1024px PNG using Quick Look (available on macOS).
# Output filename varies; we pick the first png produced.
qlmanage -t -s 1024 -o "$TMP_DIR" "$SRC_SVG" >/dev/null 2>&1 || {
  echo "[icon] qlmanage failed to render SVG. Try opening the SVG once in Preview, or install an SVG renderer." >&2
  exit 1
}

PNG_1024="$(ls -1 "$TMP_DIR"/*.png 2>/dev/null | head -n 1 || true)"
if [[ -z "$PNG_1024" ]]; then
  echo "[icon] No PNG generated by qlmanage in $TMP_DIR" >&2
  exit 1
fi

# Create required iconset sizes from the 1024 source.
for size in 16 32 128 256 512; do
  sips -z "$size" "$size" "$PNG_1024" --out "$ICONSET_DIR/icon_${size}x${size}.png" >/dev/null
  double=$((size * 2))
  sips -z "$double" "$double" "$PNG_1024" --out "$ICONSET_DIR/icon_${size}x${size}@2x.png" >/dev/null
done

iconutil -c icns "$ICONSET_DIR" -o "$OUT_ICNS"

echo "[icon] Wrote $OUT_ICNS"
